version: "3"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin

# Start containers in detached/ background mode: docker-compose up -d

# Stop containers:  docker-compose down

